### ISSUE TITLE
Contact-Us Page Enhancements

### ISSUE THREAD

**Issue by AlyafeiAli** [SpecialProjectADU/Site#92]
### These comments are from Dr. Mourad.  

- Replace "Talk to Repre..." with a chatbot
- Fix Email

Responsibility: @rahaf2201 and her team.  
Write your questions in the comments and mention Mouatism.

![image](https://github.com/SpecialProjectADU/Site/assets/52626961/0b126a9f-d795-4d51-9e83-a5524c150df5)

**Comment by rahaf2201** [comment]
Fixed.
Added a Chatbot.
Fixed Email.
Also, fixed the heading based on the standard given.
![image](https://github.com/SpecialProjectADU/Site/assets/73061653/4c8fc2e3-0807-49ec-8290-08911f9d98d9)
![image](https://github.com/SpecialProjectADU/Site/assets/73061653/e33538eb-aa74-4023-8796-918c0687b6bf)

NOTE: I will be downloading all updated files after Osama fixes the logo and I update them on all my group's pages.

**Comment by binHarby** [comment]
Your CSS selectors are over lapping as well in `StylesStylesAboutContactEventLoginSignup.css`

Mostly these ones:
```css
...
p{
  font-size: 16px;
  color: #929AAB;
}

...

.map h3{
  padding-top: 150px;
  font-weight: 1000;
  color: white;
  font-family: 'Bebas Neue', cursive;
  font-family: 'Comfortaa', cursive;
  font-size: 80px;
  
}

```

its a single css file that styles 4 pages, and the p selector is what made the title white color, which made it not showup in the contact page. 

try not to change 'color' or 'background-color' using html selectors that target many childeren. Instead use a class if you can, so when we change styles in `Global.css`,'Footer.css` or `Navbar.css`, it can go smoothly.
