### ISSUE TITLE
Shopping Cart Page Enhancements

### ISSUE THREAD

**Issue by AlyafeiAli** [SpecialProjectADU/Site#94]
### These comments are from Dr. Mourad.  

- Standards
- Remove extra margins

**Comment by binHarby** [comment]
As you could see from the `StylesShoppingCart.css` file content, I am using the standard. It was just the 'Pay' button, which i am changing right now. as for the margins, please be more specific. 

```css

.bg-element-primary {
    background-color: #393E46;
}

.bg-element-secondary {
    background-color: #929AAB;
}
.bg-bg-primary{
    background-color: #f7f7f7;
}
.bg-bg-secondary {
    background-color: #EEEEEE;


}
```
